// <auto-generated />
using System;
using DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.BankCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("CardIssue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidityPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankCards");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CardIssue = 20000m,
                            CardName = "HUMO",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "O‘zbekiston bo‘ylab barcha turdagi to‘lovlar\r\nBankomatlar orqali kartadan naqd pul yechish\r\nPul mablag‘larini kartadan kartaga o‘tkazish\r\nBank kartasida NFC xizmati mavjud",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidityPeriod = "5"
                        },
                        new
                        {
                            Id = 2L,
                            CardIssue = 50000m,
                            CardName = "UzCard",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "O‘zbekiston bo‘ylab barcha turdagi to‘lovlar\r\nBankomatlar orqali kartadan naqd pul yechish\r\nBank kartasini «Zoomrad» mobil ilovasiga ulash\r\nPul mablag‘larini kartadan kartaga o‘tkazish",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidityPeriod = "5"
                        },
                        new
                        {
                            Id = 3L,
                            CardIssue = 30000m,
                            CardName = "VISA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dunyo boʻyicha 2.6 milliondan ortiq bankomatlar\r\nNaqd shaklda xorijiy valyutani yechib olish\r\nBank kartasida NFC xizmati mavjud\r\n«Zoomrad» mobil ilovasi orqali mablagʻlarni boshqarish",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidityPeriod = "5"
                        },
                        new
                        {
                            Id = 4L,
                            CardIssue = 30000m,
                            CardName = "UzCard-UnionPay",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oʻzbekiston hududida hamda xorij mamlakatlarida toʻlovni amalga oshirish\r\nBitta kartada - ikkita toʻlov tizimi\r\nSoʻmdagi pul mablagʻlarini konvertatsiyasiz toʻlovlarni amalga oshirish",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidityPeriod = "5"
                        },
                        new
                        {
                            Id = 5L,
                            CardIssue = 30000m,
                            CardName = "UzCard-Mir",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "O‘zbekiston bo‘ylab barcha turdagi to‘lovlar\r\nBankomatlar orqali kartadan naqd pul yechish\r\nBank kartasini «Zoomrad» mobil ilovasiga ulash\r\nPul mablag‘larini kartadan kartaga o‘tkazish",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidityPeriod = "5"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Credit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreditName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lifetime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Percentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Credits");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 9, 4, 8, 9, 34, 587, DateTimeKind.Utc).AddTicks(688),
                            CreditName = "Avtokredit - birlamchi bozor uchun",
                            Description = "Birlamchi bozordan yengil avtotransport vositalarini sotib olish uchun hamda sugʻurta mukofoti toʻlovlarini toʻlash uchun ajratiladi.\r\n",
                            Lifetime = "4 yil",
                            Percentage = "24%",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditName = "Avtokredit - BYD HAN, KIA, Chery, Jetour.",
                            Description = "Birlamchi bozordan «BYD HAN», «KIA», «Chery», «Jetour», «Bestune», «Hongqi», «Dongfeng», «Mazda», «Skywell», «Foton» hamda «Shineray» avtotransport vositalarini realizatsiya qiluvchi tashkilotlar («Roodell»MCHJ, «Auto Motors Asia» MCHJ, «King Garment Textile» MCHJ, «Sher-Don-Yda» MCHJ, «MK Direct» MCHJ, «Astana Motors Company» MCHJ ) bilan tuzilgan hamkorlik shartnomasi doirasida ushbu avtotransport vositalarini sotib olish uchun.",
                            Lifetime = "5 yil",
                            Percentage = "20%",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditName = "Universal mikroqarz",
                            Description = "Har qanday maqsad uchun miqroqarz.\r\n",
                            Lifetime = "3 yil",
                            Percentage = "24%",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Deposit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepositName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinLifetime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Percentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Deposits");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepositName = "Siz Uchun",
                            Description = "Yuqori daromad olish imkoniyatidan foydalaning\r\n\r\nOnlayn ochish mumkin\r\nOmonatni to‘ldirish\r\nQisman chiqim qilish",
                            MinLifetime = "24 oy",
                            Percentage = "23%",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepositName = "«COMFORT» PLUS",
                            Description = "Omonatga mablag‘lar naqdsiz shaklda bankning mobil ilova orqali qabul qilinadi. АQSh dollarida, istalgan vaqtda qoʻshimcha mablagʻ bilan to‘ldirishingiz hamda zarurat tugʻilganda undan 100 AQSH dollari qoldiq saqlagan holda qisman chiqim qilishingiz mumkin.\r\n\r\n",
                            MinLifetime = "24 oy",
                            Percentage = "6.5%",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepositName = "«Chorak asr» online",
                            Description = "Mablagʻlaringizni oʻzingiz xohlagandek boshqarish imkoniyati mavjud. Ya'ni, sizga qulay vaqtda omonatingizni qoʻshimcha mablagʻ bilan toʻldirishingiz yoki zarurat tugʻilganda omonatingiz foizlarini saqlagan holda undan qisman chiqim qilishingiz mumkin.",
                            MinLifetime = "12 oy",
                            Percentage = "22%",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Transfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 9, 4, 8, 9, 34, 587, DateTimeKind.Utc).AddTicks(564),
                            Email = "isroilovravshan42@gmail.com",
                            FirstName = "Ravshan",
                            LastName = "Isroilov",
                            Password = "1234",
                            PhoneNumber = "+998902528196",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 9, 4, 8, 9, 34, 587, DateTimeKind.Utc).AddTicks(567),
                            Email = "oybabd@gmail.com",
                            FirstName = "Oybek",
                            LastName = "Abdurahmonov",
                            Password = "1234",
                            PhoneNumber = "+998998721027",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 9, 4, 8, 9, 34, 587, DateTimeKind.Utc).AddTicks(568),
                            Email = "Majidov@gmail.com",
                            FirstName = "Akbarali",
                            LastName = "Majidov",
                            Password = "1234",
                            PhoneNumber = "+998902528196",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 9, 4, 8, 9, 34, 587, DateTimeKind.Utc).AddTicks(568),
                            Email = "buni@gmail.com",
                            FirstName = "Bunyod",
                            LastName = "Toshmatov",
                            Password = "1234",
                            PhoneNumber = "+998900207228",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 9, 4, 8, 9, 34, 587, DateTimeKind.Utc).AddTicks(569),
                            Email = "otkir@gmail.com",
                            FirstName = "O'tkirbek",
                            LastName = "Hamidov",
                            Password = "1234",
                            PhoneNumber = "+998995629737",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
